// Native opencode custom-tools generator for the Noon shell's IPC surface.
//
// Tools are discovered, not hardcoded: `qs -p <root> ipc show` (targets +
// `function name(p: type, ...)` lines) yields one named tool export per NPC
// function. `harness gen-tools` prints the file for ~/.config/opencode/tools/.
// A small curated fallback covers the case where discovery fails.
package main

import (
	"context"
	"fmt"
	"os/exec"
	"regexp"
	"strconv"
	"strings"
	"time"
)

type tool struct {
	target string
	fn     string
	params []string
}

func (t tool) ipcName() string { return t.target + "_" + t.fn }

var fallback = []tool{
	{target: "global", fn: "toast", params: []string{"info", "state"}},
	{target: "noon", fn: "translate", params: []string{"query"}},
	{target: "global", fn: "say", params: []string{"text"}},
}

var (
	targetRe = regexp.MustCompile(`^target (\S+)\s*$`)
	fnRe     = regexp.MustCompile(`^\s*function (\w+)\(([^)]*)\)`)
)

func parseTools(out string) []tool {
	var tools []tool
	seen := map[string]bool{}
	target := ""
	for _, line := range strings.Split(out, "\n") {
		if m := targetRe.FindStringSubmatch(line); m != nil {
			target = m[1]
			continue
		}
		if target == "" {
			continue
		}
		if m := fnRe.FindStringSubmatch(line); m != nil {
			name := m[1]
			var params []string
			for _, p := range strings.Split(m[2], ",") {
				p = strings.TrimSpace(p)
				if i := strings.Index(p, ":"); i >= 0 {
					p = strings.TrimSpace(p[:i])
				}
				if p != "" {
					params = append(params, p)
				}
			}
			key := target + "_" + name
			if !seen[key] {
				seen[key] = true
				tools = append(tools, tool{target: target, fn: name, params: params})
			}
		}
	}
	return tools
}

// cmdGenTools prints a native opencode custom-tools file (one named export
// per shell IPC function) for ~/.config/opencode/tools/. Native tools ride
// the normal tool pipeline (permissions, approvals) with no MCP round trip.
func cmdGenTools(shellRoot string) error {
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()
	out, err := exec.CommandContext(ctx, "qs", "-p", shellRoot, "ipc", "show").Output()
	tools := fallback
	if err == nil {
		if parsed := parseTools(string(out)); len(parsed) > 0 {
			tools = parsed
		}
	}
	var sb strings.Builder
	sb.WriteString("// Generated by Noon shell (harness gen-tools). Do not edit by hand.\n")
	sb.WriteString("import { tool } from \"@opencode-ai/plugin\";\n\n")
	sb.WriteString("const SHELL_ROOT = " + strconv.Quote(shellRoot) + ";\n\n")
	sb.WriteString(`async function shellIpc(target: string, fn: string, params: string[], values: Record<string, unknown>): Promise<string> {
  const argv: string[] = ["qs", "-p", SHELL_ROOT, "ipc", "call", target, fn];
  for (const p of params) {
    const v = values[p];
    argv.push(v === undefined || v === null ? "" : String(v));
  }
  const proc = Bun.spawn(argv, { stdout: "pipe", stderr: "pipe" });
  const [out, err, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  const text = (out + err).trim();
  if (code !== 0)
    throw new Error(text === "" ? fn + " exited " + code : text);
  return text;
}

`)
	for _, t := range tools {
		name := t.target + "_" + t.fn
		sb.WriteString("export const " + name + " = tool({\n")
		sb.WriteString("  description: " + strconv.Quote("Noon shell: "+t.target+" "+t.fn) + ",\n")
		sb.WriteString("  args: {\n")
		for _, p := range t.params {
			sb.WriteString("    " + p + ": tool.schema.string().describe(" + strconv.Quote(p) + "),\n")
		}
		sb.WriteString("  },\n")
		sb.WriteString("  async execute(args) {\n")
		sb.WriteString("    return await shellIpc(" + strconv.Quote(t.target) + ", " + strconv.Quote(t.fn) + ", [")
		for i, p := range t.params {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(strconv.Quote(p))
		}
		sb.WriteString("], args);\n  },\n});\n\n")
	}
	fmt.Print(sb.String())
	return nil
}
