copr {
  pharmaracist/Noon
  cjatherton/zed
  abhis3k/WhatSie
}

pkgs {
  whatsie
  ark
  bluedevil
  kitty
  kdialog
  nm-connection-editor
  pavucontrol-qt
  plasma-nm
  playerctl
  systemsettings
  fuzzel
  zed
  easyeffects
  eza
  partitionmanager
  cava
  neovim
  dolphin
  firefox
  btop
  satty
  mpv
  gpu-screen-recordery
}
