pkgs {
  git
  libdrm
  gcc
  libglvnd
  jemalloc
  clang
  cmake
  ninja-build
  meson
  cairomm
  glib2
  gobject-introspection
  gtkmm3.0
  gvfs
  libdbusmenu-gtk3
  libportal-gtk4
  libsoup3
  sassc
  tinyxml2
}

# Qt6
pkgs {
  qt6-qtshadertools-devel
  qt6-qtbase qt6-qtdeclarative qt6-qt5compat
  qt6-qtimageformats qt6-qtmultimedia
  qt6-qtpositioning qt6-qtquicktimeline
  qt6-qtsensors qt6-qtsvg qt6-qttools
  qt6-qttranslations qt6-qtvirtualkeyboard
  qt6-qtwayland qt6-qtwebsockets
}
# KF
pkgs {
    kf6-kguiaddons-devel
}
