# COPR
copr {
  achno/gowall
  deltacopy/darkly
  pharmaracist/Noon
  mradityaalok/satori
  rivenirvana/gamemode
  ashbuk/Hyprland-Fedora
}

# PYTHON
python {
  mpv
  click
  loguru
  psutil
  yt-dlp
  ytmusicapi
  requests_oauth2client
}

# HYPRLAND
pkgs {
  hyprland hyprcursor hypridle hyprlock
  hyprpicker hyprutils
  hyprwayland-scanner hyprland-protocols-devel
  xdg-desktop-portal-hyprland
  hyprland-guiutils hyprtoolkit
}

# Misc
pkgs {
  auto-cpufreq
  sddm
  polkit-kde-agent-1
  NetworkManager
  wireplumber
  upower
  gammastep
  geoclue2
  kwallet
  quickshell
  pipewire
  axel
  tldr
  bc
  brightnessctl
  wl-clipboard
  grim
  grimblast
  coreutils
  curl
  ddcutil
  figlet
  fish
  pokemon-colorscripts
  jq
  ripgrep
  rsync
  tesseract
  tesseract-langpack-eng
  translate-shell
  wget
  xdg-user-dirs
  ydotool
  ntfs-3g
  uv
  darkly
  matugen
  cliphist
  tmux
  gowall
  bluez
  openssh
  v4l2loopback
  xdg-desktop-portal

  # GTK
  adw-gtk3-theme
  fontconfig
  gtk4
  libadwaita
  hicolor-icon-theme
  xdg-desktop-portal-gtk
}
