# Apps
pkgs {
  ark bluedevil foot kdialog
  nm-connection-editor pavucontrol-qt plasma-nm playerctl
  qalculate-qt systemsettings vlc quickshell-git wf-recorder
  fuzzel mpv mpd-mpris zed telegram-desktop-bin vesktop-bin
  obsidian vscodium-bin spotify spicetify-cli
  spicetify-marketplace-bin yt-dlg cava easyeffects
  obs-studio calf lsp-plugins zathura zathura-pdf-mupdf
  nwg-look stow perplexity eza
  pokemon-colorscripts-go partitionmanager wine-staging
}

# Dev
pkgs {
  clang cmake meson ninja git
  cairomm glib2 gobject-introspection gtkmm3 gtksourceviewmm
  gvfs libdbusmenu-gtk3 libportal-gtk4 libratbag
  libsoup3 sassc tinyxml2
  qt6-base qt6-declarative qt6-5compat
  qt6-imageformats qt6-multimedia qt6-positioning
  qt6-quicktimeline qt6-sensors qt6-svg
  qt6-tools qt6-translations qt6-virtualkeyboard
  qt6-wayland qt6-websockets
  python-click python-loguru python-psutil
}

# WM
pkgs {
  hyprland hyprcursor hypridle hyprlock
  hyprpicker hyprsunset hyprutils
  hyprwayland-scanner hyprland-protocols
  hyprland-qt-support
  xdg-desktop-portal xdg-desktop-portal-gtk
  sddm polkit-kde-agent networkmanager
  wireplumber upower gammastep geoclue
  gnome-keyring kwallet ananicy-cpp
}

# Misc
pkgs {
  axel bc brightnessctl wl-clipboard grimblast-git
  coreutils curl ddcutil figlet fish jq
  ripgrep rsync tesseract tesseract-data-eng
  translate-shell wget xdg-user-dirs ydotool
  ntfs-3g uv
}

pkgs {
  adw-gtk-theme adw-gtk-theme-git
  archlinux-xdg-menu fontconfig gtk4 libadwaita
  kde-material-you-colors gowall matugen-bin darkly-bin
}

pkgs {
  heroic-games-launcher gamemode lib32-gamemode
  vkd3d lib32-vkd3d steam gamescope
}

pkgs {
  hicolor-icon-theme jemalloc libglvnd libdrm
  gcc-libs v4l2loopback-dkms v4l2loopback-utils
}

script {
  setup-mirsald.sh
}
