pkgs {
  nvidia-open-dkms nvidia-utils
  lib32-nvidia-utils lib32-opencl-nvidia
  libva-nvidia-driver egl-wayland
}

pkgs {
  nvidia-580xx-dkms nvidia-580xx-utils
  opencl-nvidia-580xx lib32-nvidia-580xx-utils
  lib32-opencl-nvidia libva-nvidia-driver egl-wayland
}

script {
  setup_nvidia.sh
}
