require("lua.variables")
require("colors")
require("lua.hacks")
require("lua.monitors")
require("lua.general")
require("lua.qs_binds")
require("lua.binds")
require("lua.rules")
require("lua.plugins")
require("lua.execs")
require("lua.env")
require("lua.input")
require("lua.animations." .. animation_style)
require("lua.effects.main")
